### ISSUE TITLE
Add TypeChain to ChugSplash contracts (contract ABI types)

### ISSUE THREAD

**Issue by RPate97** [sphinx-labs/sphinx#726]
## Problem
We don't have any TypeScript bindings for our contract ABIs. This means we're basically using JavaScript when calling contract functions in TypeScript.

## Solution
https://github.com/dethcrypto/TypeChain
TypeChain is an open-source package that adds TypeScript bindings to your contract ABIs. We should use it to generate types for our contracts and then use those types when interacting with the contracts from Typescript.

**Comment by lazyfuhrer** [comment]
assigne me @RPate97

**Comment by yorhodes** [comment]
Typechain has been deprecated

**Comment by RPate97** [comment]
> Typechain has been deprecated

Thanks!
