### ISSUE TITLE
Document Async Config Files

### ISSUE THREAD

**Issue by RPate97** [sphinx-labs/sphinx#729]
## Problem
We allow users to define ChugSplash configs which are resolved asynchronously by using an asynchronous function as the default export in their config file. However, we do not document this feature.

## Context
For example, the following config file works properly as long as the `HelloChugSplash` contract has only the `chainId` variable in it:
```
import { UserChugSplashConfig } from '@chugsplash/core'
import '@nomiclabs/hardhat-ethers'
import hre, { ethers } from 'hardhat'

const resolveConfig = async (): Promise<UserChugSplashConfig> => {
  const chainId = await hre.ethers.provider
    .getNetwork()
    .then((network) => network.chainId)

  return {
    options: {
      organizationID: ethers.constants.HashZero,
      projectName: 'Hello ChugSplash',
    },
    contracts: {
      MyFirstContract: {
        contract: 'HelloChugSplash',
        variables: {
          chainId,
        },
      },
    },
  }
}

export default resolveConfig
```

## Solution
We should create a document on using asynchronous functions to define ChugSplash configs, provide some examples of doing it an use cases for it, and then update our getting started guides to note that it is possible and link to the document.

**Comment by AnmolSirola** [comment]
@RPate97 Can I work on this issue?

**Comment by RPate97** [comment]
> @RPate97 Can I work on this issue?

Go for it! Feel free to @ me if you have any questions!
